/*
 * Generated by XDoclet - Do not edit!
 */
package com.sidorykp.ejb.ejb2test1;

/**
 * Remote interface for My1.
 * @generated 
 * @wtp generated
 */
public interface My1
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

}
