/*
 * Generated by XDoclet - Do not edit!
 */
package com.sidorykp.ejb.ejb2test1;

/**
 * Home interface for My1.
 * @generated 
 * @wtp generated
 */
public interface My1Home
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/My1";
   public static final String JNDI_NAME="My1";

   public com.sidorykp.ejb.ejb2test1.My1 create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
