/*
 * Generated by XDoclet - Do not edit!
 */
package com.sidorykp.ejb.ejb2test1;

/**
 * Local home interface for My1.
 * @generated 
 * @wtp generated
 */
public interface My1LocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/My1Local";
   public static final String JNDI_NAME="My1Local";

   public com.sidorykp.ejb.ejb2test1.My1Local create()
      throws javax.ejb.CreateException;

}
