/*
 * Generated by XDoclet - Do not edit!
 */
package com.sidorykp.ejb.ejb2test1;

/**
 * Local interface for My1.
 * @generated 
 * @wtp generated
 */
public interface My1Local
   extends javax.ejb.EJBLocalObject
{

}
